# Generated by Django 2.0.4 on 2018-05-22 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapSnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Capture Time')),
                ('open_seats', models.IntegerField(verbose_name='Open Seats')),
                ('reserved_seats', models.IntegerField(verbose_name='Reserved Seats')),
                ('taken_seats', models.IntegerField(verbose_name='Taken Seats')),
                ('waiting', models.IntegerField(verbose_name='Waiting')),
                ('closed', models.BooleanField(verbose_name='Closed')),
            ],
            options={
                'verbose_name': 'Capacity Snapshot',
                'ordering': ['time'],
                'get_latest_by': 'time',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Class Name')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_shortname', models.CharField(max_length=3, verbose_name='Quarter Shortname')),
                ('se_first', models.DateField(blank=True, null=True, verbose_name='Special Exception 1st Round')),
                ('se_second', models.DateField(blank=True, null=True, verbose_name='Special Exception 2nd Round')),
                ('cgs_first', models.DateField(blank=True, null=True, verbose_name='Continuing Graduate Students 1st Round')),
                ('cgs_second', models.DateField(blank=True, null=True, verbose_name='Continuing Graduate Students 2nd Round')),
                ('apl4_first', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level IV 1st Round')),
                ('apl4_second', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level IV 2nd Round')),
                ('apl3_first', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level III 1st Round')),
                ('apl3_second', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level III 2nd Round')),
                ('apl2_first', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level II 1st Round')),
                ('apl2_second', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level II 2nd Round')),
                ('apl1_first', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level I 1st Round')),
                ('apl1_second', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level I 2nd Round')),
                ('pnc_first', models.DateField(blank=True, null=True, verbose_name='PolyPlanner Non-Compliant 1st Round')),
                ('pnc_second', models.DateField(blank=True, null=True, verbose_name='PolyPlanner Non-Compliant 2nd Round')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(editable=False, verbose_name='Class Number')),
                ('section_num', models.IntegerField(verbose_name='Section Number')),
                ('class_type', models.CharField(max_length=4, verbose_name='Type')),
                ('instructor', models.CharField(max_length=40, verbose_name='Instructor')),
                ('days', models.CharField(max_length=5, verbose_name='Days')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('building', models.CharField(max_length=40, verbose_name='Building')),
                ('room', models.CharField(max_length=10, verbose_name='Room')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass_app.Class')),
                ('quarter', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pass_app.Quarter')),
            ],
        ),
        migrations.AddField(
            model_name='capsnap',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass_app.Section'),
        ),
    ]
