# Generated by Django 2.0.2 on 2018-02-20 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapSnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Capture Time')),
                ('open_seats', models.IntegerField(verbose_name='Open Seats')),
                ('reserved_seats', models.IntegerField(verbose_name='Reserved Seats')),
                ('taken_seats', models.IntegerField(verbose_name='Taken Seats')),
                ('waiting', models.IntegerField(verbose_name='Waiting')),
                ('closed', models.BooleanField(verbose_name='Closed')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('class_number', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Class Number')),
                ('section_num', models.IntegerField(verbose_name='Section Number')),
                ('class_type', models.CharField(max_length=4, verbose_name='Type')),
                ('instructor', models.CharField(max_length=40, verbose_name='Instructor')),
                ('days', models.CharField(max_length=5, verbose_name='Days')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('building', models.CharField(max_length=40, verbose_name='Building')),
                ('room', models.CharField(max_length=6, verbose_name='Room')),
            ],
        ),
        migrations.AddField(
            model_name='capsnap',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass_app.Section'),
        ),
    ]
