# Generated by Django 2.0.4 on 2018-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0002_auto_20180220_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_shortname', models.CharField(max_length=3, verbose_name='Quarter Shortname')),
                ('se_first', models.DateField(blank=True, null=True, verbose_name='Special Exception 1st Round')),
                ('se_second', models.DateField(blank=True, null=True, verbose_name='Special Exception 2nd Round')),
                ('cgs_first', models.DateField(blank=True, null=True, verbose_name='Continuing Graduate Students 1st Round')),
                ('cgs_second', models.DateField(blank=True, null=True, verbose_name='Continuing Graduate Students 2nd Round')),
                ('apl4_first', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level IV 1st Round')),
                ('apl4_second', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level IV 2nd Round')),
                ('apl3_first', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level III 1st Round')),
                ('apl3_second', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level III 2nd Round')),
                ('apl2_first', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level II 1st Round')),
                ('apl2_second', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level II 2nd Round')),
                ('apl1_first', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level I 1st Round')),
                ('apl1_second', models.DateField(blank=True, null=True, verbose_name='Academic Progress Level I 2nd Round')),
                ('pnc_first', models.DateField(blank=True, null=True, verbose_name='PolyPlanner Non-Compliant 1st Round')),
                ('pnc_second', models.DateField(blank=True, null=True, verbose_name='PolyPlanner Non-Compliant 2nd Round')),
            ],
        ),
        migrations.AlterModelOptions(
            name='capsnap',
            options={'get_latest_by': 'time', 'verbose_name': 'Capacity Snapshot'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
    ]
