# Generated by Django 2.0.4 on 2018-05-21 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0003_auto_20180520_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='quarter',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pass_app.Quarter'),
        ),
    ]
