# Generated by Django 2.0.4 on 2018-05-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0004_section_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='room',
            field=models.CharField(max_length=10, verbose_name='Room'),
        ),
    ]
