# Generated by Django 2.0.4 on 2018-05-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0005_auto_20180521_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsnap',
            name='time',
            field=models.DateTimeField(verbose_name='Capture Time'),
        ),
    ]
